server:
  port: 3344
spring:
  application:
    name: cloud-config-center3344
  cloud:
    config:
      server:
        git:
          uri: git@github.com:ljx-p/SpringCloud-Config.git
          #对应的是GitHub上面的Git仓库的名称
          search-paths:
            - SpringCloud-Config
      label: master
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
