server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称  这个名称在host文件里面进行了映射
  client:
    register-with-eureka: false #表示不向注册中心注册自己
    fetch-registry: false #表示自己就是就是注册中心,用来维护服务的实例,并不需要去检索服务
    service-url:
      #设置与EurekaServer交互的地址查询服务和注册服务都需要依赖这个地址
      #      defaultZone: http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/