server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址  lb://xxx都是这一种格式进行管理
          predicates:
            - Path=/select/**         # 断言，路径相匹配的进行路由
#            - After=2020-09-18T09:50:44.151+08:00[Asia/Shanghai]  #只有在9:50之后才可以进行调用
        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/lb/**         # 断言，路径相匹配的进行路由
            - After=2020-09-18T09:50:44.151+08:00[Asia/Shanghai]
            #标志只有在这个时间之后断言才会起作用  在这个时间段之前无论是怎么访问都是不会有作用的
            #- Cookie=username,zzyy
            #- Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true #服务提供者provider注册进eureka服务列表内
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/



