server:
  port: 88
spring:
  application:
    name: cloud-consumerConsul-order
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}