spring:
  application:
    name: cloud-consumer-feign-hystrix
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
server:
  port: 88
feign:
  hystrix:
    enabled: true #在feign里面开启Hystrix